# .github/FUNDING.yml
patreon: yourPatreonName
open_collective: r3c-foundation
ko_fi: yourKoFiName
buy_me_a_coffee: yourname
custom:
  - https://opencollective.com/r3c-foundation
  - https://buymeacoffee.com/yourname
