github: 0200134
open_collective: r3c-foundation
patreon: r3cfoundation
ko_fi: r3cfoundation
buy_me_a_coffee: r3cfoundation

custom:
  - https://opencollective.com/r3c-foundation
  - https://buymeacoffee.com/r3cfoundation
