name: "💡 Feature Request"
description: "새로운 기능을 제안합니다"
title: "[Feature] "
labels: ["enhancement"]

body:
  - type: input
    id: summary
    attributes:
      label: "요약"
      description: "추가하고 싶은 기능의 간단한 요약을 작성해주세요."
      placeholder: "예: Rust→ASM 변환 규칙 개선"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "배경 및 필요성"
      description: "이 기능이 왜 필요한지, 어떤 문제를 해결하는지 설명해주세요."
      placeholder: |
        예: 
        - 현재 Rust→ASM 변환 시 특정 레지스터 최적화가 누락됩니다.
        - 빌드 타임 단축을 위해 병렬 처리 옵션이 필요합니다.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "세부 내용"
      description: "기능 동작 방식, CLI 명령어, API 예시 등을 자세히 적어주세요."
      placeholder: |
        예시:
        - 새로운 Rust→NASM 변환 규칙 추가
        - `r3c.exe --lint` 옵션 지원
        - `cpppm add --from-git` 명령어 추가
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "우선순위"
      description: "이 기능의 중요도를 선택해주세요."
      options:
        - 낮음
        - 보통
        - 높음
