name: 🚀 New Feature / Contribution Proposal
description: Suggest a feature, improvement, or area you want to contribute to R3C
title: "[feature]: "
labels: ["feature", "contribution", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧩 Thank you for contributing to R3C!
        Please describe your idea below.  
        Before submitting, check open issues to avoid duplicates.

  - type: input
    id: summary
    attributes:
      label: 🔖 Short summary
      description: "One-line description of your idea"
      placeholder: "Add Linux NASM backend"

  - type: textarea
    id: details
    attributes:
      label: 📄 Details
      description: "Explain what your contribution will do and why it's useful"
      placeholder: "This feature adds emit_linux() to support ELF64 output for NASM builds."

  - type: dropdown
    id: category
    attributes:
      label: 🧠 Area
      options:
        - Parser Engine
        - NASM Backend
        - Refactor Engine
        - Docs / Comments
        - Tests / CI
        - Diagnostics / UX
        - Branding / Logo
        - Security / Hardening
        - Other

  - type: dropdown
    id: difficulty
    attributes:
      label: ⚙️ Estimated Difficulty
      options:
        - 🟢 Easy
        - 🟡 Medium
        - 🔴 Hard

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Contributor Checklist
      options:
        - label: "I've built the project locally with `cmake --build build`"
          required: true
        - label: "I've reviewed CONTRIBUTING.md"
          required: true
        - label: "This is not a duplicate of an existing issue"
          required: true
