name: "π“ Spec Proposal"
description: "Rust 3.0 λ…μ„Έ(R3C Spec)μ— λ€ν• λ³€κ²½ μ μ•"
title: "[Spec] "
labels: ["spec", "discussion"]
body:
  - type: input
    id: section
    attributes:
      label: "κ΄€λ ¨ λ…μ„Έ μ„Ήμ…"
      placeholder: "μ: 5.2 Memory Model / 6.1 NASM Pipeline"
  - type: textarea
    id: summary
    attributes:
      label: "λ³€κ²½ μ μ• μ”μ•½"
      description: "μ–΄λ–¤ λ³€κ²½ λλ” μ¶”κ°€λ¥Ό μ μ•ν•λ”μ§€ μ”μ•½"
  - type: textarea
    id: rationale
    attributes:
      label: "μ μ• μ΄μ  / λ°°κ²½"
      description: "μ΄ μ μ•μ΄ μ™ ν•„μ”ν•μ§€ μ„¤λ…"
  - type: textarea
    id: impact
    attributes:
      label: "μν–¥λ„ λ¶„μ„"
      description: "μ΄ λ³€κ²½μ΄ νΈλμ¤νμΌλ¬, ν‘μ¤€ λΌμ΄λΈλ¬λ¦¬, λλ” ABIμ— λ―ΈμΉλ” μν–¥"
  - type: checkboxes
    id: compatibility
    attributes:
      label: "ν•μ„ νΈν™μ„± μν–¥ μ—¬λ¶€"
      options:
        - label: "κΈ°μ΅΄ μ½”λ“μ™€ νΈν™ μ μ§€λ¨"
        - label: "λ¶€λ¶„μ  λΉ„νΈν™μ„± μ΅΄μ¬"
        - label: "μ™„μ „ν• λΉ„νΈν™ λ³€κ²½"
