name: Update Contributors
on:
  schedule:
    - cron: '0 12 * * 1' # 매주 월요일 자동 업데이트
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add contributors
        uses: all-contributors/all-contributors-action@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit: false
