name: Automate Discussion Documentation

on:
  schedule:
    - cron: '0 0 * * SUN'  # 매주 일요일 자정
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests
    - name: Fetch discussions and update docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/fetch_discussions.py
    - name: Commit & Push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add docs/community_feedback.md
        git commit -m "chore: Update community feedback log"
        git push
      continue-on-error: true
